services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: todo-backend
    ports:
      - "5001:5001"
    volumes:
      - db_data:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  db_data: